Repository algorandfoundation/xGov, pull requests merged in 2023-11, with the labels that each got.

#93 xgov-93: Community PVP tournament
  Proposals/xgov-93.md
Labels: t-community, a-user_onboarding, s-final

#85 xgov-85
  Proposals/xgov-85.md
Labels: s-final, t-tools, a-nft

#90 xgov-90: AWallet scheduler
  Proposals/xgov-90.md
Labels: o-open_source, s-final, t-tools, a-banking

#87 xGov-87: Alright
  Proposals/xgov-87.md
Labels: o-open_source, s-final, t-dapps

#86 xGov-86: Bonfire 🔥
  Proposals/xgov-86.md
Labels: o-open_source, s-final, t-tools, a-defi

#84 xgov-84: Decentralized liquidity aggregator & lending platform by Vestige
  Proposals/xgov-84.md
Labels: o-open_source, s-final, t-dapps, a-defi

#82 xgov-82: Prague community meetups
  Proposals/xgov-82.md
Labels: t-community, o-open_source, a-user_onboarding, s-final

#81 xgov-81: VoteCoin - DAO Liquidity
  Proposals/xgov-81.md
Labels: t-community, o-open_source, a-user_onboarding, s-final

#80 XGov80: Open source concentrated liqudity AMM
  Proposals/xgov-80.md
Labels: o-open_source, s-final, t-dapps, a-defi

#79 XGov79: VoteCoin - GitHub tools
  Proposals/xgov-79.md
Labels: t-community, o-open_source, s-final, a-deployment

#77 xGov-77: AlgoVerify - Secure Verification System
  Proposals/xgov-77.md
Labels: o-open_source, s-final, t-tools

#74 xGov-74: Notiboy web3 chat application
  Proposals/xgov-74.md
Labels: o-open_source, a-user_onboarding, s-final, t-dapps

#72 xGov-72:Proposal to monitor Algorand Inc Algo spending
  Proposals/xgov-72.md
Labels: o-open_source, s-final, t-tools, a-monitoring

#71 xGov-71: Milestone 2 - ASA Stats tax reporting reference
  Proposals/xgov-x.md
Labels: s-final, t-tools, a-defi

#70 xGov-70: Securing ASA Stats API high availability for the next 2 years
  Proposals/xgov-70.md
Labels: s-final, t-tools

#53 xGov-53 Subscriptions! Recurrent Payments & Contract Calls Platform
  Proposals/xgov-53.md
Labels: o-open_source, s-final, t-dapps, a-defi

#50 xGov-50 Sureblocks proposal for Algorand
  Proposals/xgov-50.md
Labels: s-final, t-dapps, a-nft

#35 xGov-35: Stable Cometa Staking
  Proposals/xgov-35.md
Labels: o-open_source, s-final, t-dapps, a-defi

#55 xGov-55: GoPlausible MultiChain Proposal
  Proposals/xgov-55.md
Labels: o-open_source, s-final, t-tools, a-nft
