Repository algorandfoundation/xGov, pull requests merged in 2023-07, with the labels that each got.

#6 xGov-6 Transaction Builder UI
  .gitignore
  Proposals/xgov-6.md
  assets/xgov-6/compose_tx_app_call_blank.png
  assets/xgov-6/compose_tx_keyreg_filled.png
  assets/xgov-6/send_tx_success.png
  assets/xgov-6/sign_tx_signed.png
Labels: o-open_source, a-user_onboarding, s-final, t-tools

#8 xGov-8 - Evil Tools
  Proposals/xGov-8.md
Labels: a-user_onboarding, s-final, t-tools

#9 xGov-9 - AWallet
  Proposals/xgov-9.md
Labels: o-open_source, s-final, t-tools

#14 Proposal for xGov 14
  Proposals/xgov-14.md
Labels: o-open_source, s-final, t-tools

#17 xGov-17 - ASA Stats Point in Time - tax reporting reference for US citizens
  Proposals/xgov-17.md
Labels: s-final, t-tools, a-defi

#18 xGov-18 - coq-avm library
  Proposals/xgov-18.md
Labels: o-open_source, s-final, t-tools, a-teal

#19 xGov-19 - Proposal to monitor the Algorand Foundation market operations
  Proposals/xgov-19.md
Labels: o-open_source, s-final, t-tools, a-monitoring

#23 xGov-23 - OpenAMM
  Proposals/xgov-23.md
Labels: o-open_source, s-final, t-dapps, a-defi

#24 xGov-24 - VoteCoin - GitHub tools
  Proposals/xgov-24.md
Labels: t-community, o-open_source, s-final, a-deployment

#26 xGov-26 - ASA Stats Offer - Algorand blockchain ASA/NFT creators' channel
  Proposals/xgov-26.md
Labels: o-open_source, a-user_onboarding, s-final, t-tools

#28 Create xGov-28 - Algorand SVM Chain Proposal.md
  Proposals/xgov-28.md
Labels: o-open_source, s-final, t-tools, a-deployment

#31 xGov-31 - Add arbitrary decimal precision exp log pow to AVM
  Proposals/xgov-31.md
Labels: o-open_source, s-final, t-tools, a-defi

#33 xGov-33 - FairTransfer
  Proposals/xgov-33.md
Labels: o-open_source, s-final, t-dapps, a-defi

#34 xGov-34 - Algorand-Monero Swaps
  Proposals/xgov-34.md
Labels: o-open_source, s-final, t-dapps

#37 xGov-37 - NFT Lending – dApp
  Proposals/xgov-37.md
Labels: o-open_source, s-final, t-dapps, a-defi

#38 xGov-38 - Decentralized Perpetual Margin Exchange
  Proposals/xgov-38.md
Labels: o-open_source, s-final, t-dapps, a-defi

#39 Proposal to build a Humble.sh connector for Hummingbot client
  Proposals/xgov-39.md
Labels: o-open_source, s-final, t-tools

#41 xGov-41: minthol, the next-gen loyalty program platform
  Proposals/xgov-41.md
Labels: s-final, t-tools, a-nft

#42 Project Galapago Instant NFT Lending XGov Grant Proposal
  Proposals/xgov-42.md
Labels: o-open_source, s-final, t-dapps, a-defi

#49 xGov-49-Solid Algo Wallet Library.md
  Proposals/xgov-49.md
Labels: o-open_source, s-final, t-tools, a-libraries

#20 Xgov- 20 -Proposal to Transform Gaming on Algorand
  Proposals/xgov-20.md
Labels: t-community, s-final, a-gaming

#43 xGov-43: Choice Coin Compliance
  Proposals/xgov.43.md
Labels: o-open_source, s-final, t-dapps, a-banking
