Repository algorandfoundation/xGov, pull requests merged in 2024-05, with the labels that each got.

#208 xGov-208 - DigiLeaf Electric Vehicle Chargers
  Proposals/xgov-208.md
Labels: s-final, p-3, f-proactive

#206 xGov-206 Tealscript (and/or PyTeal) interactive developer course (AgorApp)
  Proposals/xgov-206.md
Labels: a-education, o-open_source, s-final, t-tools, p-4, f-proactive

#205 xGov-205: Cosmic Champs P2E game - RETROACTIVE
  Proposals/xgov-205.md
Labels: t-community, s-final, a-gaming, p-4, f-retroactive

#204 xGov-204 Everyone Launchpad Security Audit
  Proposals/xgov-204.md
Labels: s-final, t-dapps, a-defi, p-4, f-proactive

#203 xGov 203 - WARN..SCAM bot
  Proposals/xgov-203.md
Labels: s-final, a-monitoring, p-4, f-retroactive

#202 xgov-202 Pact.fi Retroactive Stableswaps
  Proposals/xgov-202.md
Labels: o-open_source, s-final, t-dapps, p-4, f-retroactive

#201 xGov-201: Cometa Launchpad (open-sourced)
  Proposals/xgov-201.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-4, f-proactive

#200 xGov#200 - Biatec Identity
  Proposals/xgov-200.md
Labels: o-open_source, s-final, t-dapps, a-identity, p-4, f-proactive

#199 xGov#199 - AWallet - Retroactive
  Proposals/xgov-199.md
Labels: o-open_source, a-user_onboarding, s-final, t-tools, p-4, f-retroactive

#196 xGov-196 - TealCraft: Remix like IDE for TealScript
  Proposals/xgov-196.md
Labels: o-open_source, s-final, t-tools, p-4, f-retroactive, a-ide

#195 xgov-195-arcpay.md
  Proposals/xgov-195.md
Labels: o-open_source, s-final, t-dapps, a-banking, p-4, f-proactive

#194 xGov-194-Gunny Rush new features and improvements
  Proposals/xgov-194.md
Labels: s-final, a-gaming, p-4, f-proactive

#192 xgov-192-PiPhi Network-Smart Home Visualization Platform
  Proposals/xgov-192.md
Labels: s-final, p-4, f-proactive

#186 xGov-186: TxnLab Use-Wallet
  Proposals/xgov-186.md
Labels: o-open_source, s-final, t-tools, a-libraries, p-4, f-retroactive

#184 xGov-184: Algorand Scam Detector & RWA tokenization insights on Algorand
  Proposals/xgov-184.md
Labels: s-final, t-tools, a-monitoring, p-4, f-retroactive

#183 xGov 183: Choice Coin Compliance
  Proposals/xgov-183.md
Labels: o-open_source, s-final, t-dapps, p-4, f-proactive

#182 xGov-182: Integrating Algorand to Airgap vault & wallet via isolated modules
  Proposals/xGov-182.md
Labels: o-open_source, s-final, t-tools, a-deployment, p-4, f-proactive

#181 xGov-181-Research Article on Algorand Voting Technologies
  Proposals/xGov180.md
Labels: o-open_source, s-final, p-4, f-proactive

#180 xGov-180: Thurstober Digital Studios - Open Source, No Code Tools
  Proposals/xGov-180.md
Labels: o-open_source, a-user_onboarding, s-final, t-tools, p-4, f-proactive

#197 xGov-197 - CompX - xUSD -> COMPX Staking
  Proposals/xgov-197.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-4, f-proactive

#198 xGov-198 - CompX - Auto-Compounding Farms
  Proposals/xgov-198.md
Labels: s-final, t-dapps, a-defi, p-4, f-retroactive

#187 xGov-187 - AlgoMinter - NFT Image Generator
  Proposals/xGov-187.md
Labels: o-open_source, s-final, t-dapps, a-nft, p-4, f-retroactive

#178 xGov 178: SIWA - Sign In With Algorand
  Proposals/xgov-178.md
Labels: o-open_source, s-final, t-tools, a-libraries, p-4, f-proactive
