Repository algorandfoundation/xGov, pull requests merged in 2024-02, with the labels that each got.

#170 xGov 170: Agreement Signing & Voting for Everyone
  Proposals/xgov-170.md
Labels: o-open_source, s-final, t-dapps, p-3

#168 xGov-168: Pact.fi Marketing Initiatives
  Proposals/xgov-168.md
Labels: s-final, t-dapps, p-3

#167 xGov 167: Token CEX Listing for Meld Gold
  Proposals/xgov-167.md
Labels: t-community, s-final, a-defi, p-3

#165 xGov 165: Proposal to build NFT Bridge between Algorand and EVM based networks
  Proposals/xgov-165.md
Labels: o-open_source, s-final, t-tools, a-nft, p-3

#164 xGov 164: Prague community meetup
  Proposals/xgov-164.md
Labels: t-community, o-open_source, a-user_onboarding, s-final, p-3

#163 xGov 163: Biatec AMM - Milestone 3
  Proposals/xgov-163.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-3

#162 xGov 162: ASA.Gold
  Proposals/xgov-162.md
Labels: t-community, o-open_source, a-user_onboarding, s-final, p-3

#161 xGov 161: VoteCoin - Introduction Video
  Proposals/xgov-161.md
Labels: t-community, o-open_source, a-user_onboarding, s-final, p-3

#160 xGov 160: Onchain voting for github projects
  Proposals/xgov-160.md
Labels: t-community, o-open_source, s-final, a-deployment, p-3

#158 xGov-158: X-NFT Cardano Integration
  Proposals/xgov-158.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-3

#157 xGov-157: Centralised Bridge Proposal: Two-Way Cardano (ADA) to Algorand (Algo)
  Proposals/xgov-157.md
Labels: s-final, t-dapps, a-defi, p-3

#156 xGov-156 - Open Source ARC53 Tooling
  Proposals/xgov-156.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-3

#154 xGov-154: Cosmic Champs partnering with legendary indie toy company to bring physical toys in-game on Algorand
  Proposals/xgov-154.md
Labels: t-community, a-user_onboarding, s-final, p-3

#153 xGov-153: Neighborhood Rideshare Project (use case)
  Proposals/xgov-153.md
Labels: s-final, t-dapps, a-deployment, p-3

#152 xGov-152: Algorand is THE chain for Gaming (establishing the RWA narrative)
  Proposals/xgov-152.md
Labels: t-community, a-user_onboarding, s-final, p-3

#150 xGov -150 - Cross-Chain community promotion and collaberation
  Proposals/xgov-150.md
Labels: t-community, s-final, p-3

#149 xGov-149 - CompX - Farm Rewards with Lock Weighting
  Proposals/xgov-149.md
Labels: s-final, t-dapps, a-defi, p-3

#145 xGov-145: Providing content to encourage on-chain activities among Algorand's Japanese users and acquiring new users.
  Proposals/xgov-145.md
Labels: t-community, a-education, s-final, p-3

#144 xGov-144: Cosmic Champs x AlgoLeagues - Cross-community 3D NFT Collab
  Proposals/xgov-144.md
Labels: t-community, s-final, a-gaming, p-3

#143 xGov-143: Solluna Mushroom Farm LLC
  Proposals/xGov-143.md
Labels: t-community, o-open_source, s-final, p-3

#142 xGov-142: Composable Marketplace by Asalytic
  Proposals/xgov-142.md
Labels: o-open_source, s-final, t-tools, a-nft, p-3

#141 xGov-141: Securing ASA Stats API high availability for the next 2 years (Milestone 2)
  Proposals/xgov-141.md
Labels: s-final, t-tools, p-3

#130 xGov-130: Community Code Contribution Contest (C4)
  Proposals/xgov-130.md
Labels: t-community, o-open_source, s-final, a-libraries, p-3

#122 xGov-122: Fast Cometa & New features
  Proposals/xgov-122.md
Labels: s-final, t-dapps, a-defi, p-3

#121 xGov-121: The Next Block Proposal to Expand on Algorand Marketing and Relevant Content
  Proposals/xgov-121.md
Labels: t-community, a-education, o-open_source, s-final, p-3

#120 xgov-120 - How to ALGO NFT - Explore our resources, tutorials, and community insights to become an Algorand NFT expert
  Proposals/xgov-120.md
Labels: o-open_source, a-user_onboarding, s-final, t-dapps, p-3

#119 xgov-119 - Zorkin - Social Login for Self-Custodial Account Authentication with ZK-SNARKs
  Proposals/xgov-119.md
Labels: o-open_source, a-user_onboarding, s-final, t-dapps, p-3

#118 xgov-118.md pressdot - The First WebMarket
  Proposals/xgov-118.md
Labels: s-final, t-dapps, p-3

#117 xGov-117 - Contract Based Wallet Abstraction
  Proposals/xgov-117.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-3

#116 xGov-116 - Subscription Payments
  Proposals/xgov-116.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-3

#114 xgov-114 - Thurstober Claims - Easily Create and Claim Atomic Swaps
  Proposals/xgov-114.md
Labels: o-open_source, a-user_onboarding, s-final, t-tools, p-3

#113 xgov-113 - Thurstober Wallet Enhancer - Asset Details and Atomic Swaps
  Proposals/xgov-113.md
Labels: o-open_source, a-user_onboarding, s-final, t-tools, p-3

#112 xgov-112 - Thurstober Tools - Onboarding Enhancements, Upgrades, and Redesign
  Proposals/xgov-112.md
Labels: o-open_source, a-user_onboarding, s-final, t-tools, p-3

#110 xGov-110 - Pixelnode: One-click node manager
  Proposals/xgov-110.md
Labels: s-final, t-tools, a-node, p-3

#109 xGov-109 - Unraveling Algorand's Real World Assets Landscape & DEX Swaps - by Chaintrail
  Proposals/xgov-109.md
Labels: s-final, t-tools, a-monitoring, p-3

#107 xGov 107 - Algorand DAO management platform
  Proposals/xgov-107.md
Labels: o-open_source, s-final, t-dapps, p-3

#104 xGov-104 Notiboy web3 chat (Milestone 2) Group Chat, Encryption and NFD integration
  Proposals/xGov-104.md
Labels: o-open_source, a-user_onboarding, s-final, t-dapps, p-3

#100 xGov-100 - GPU-based vanity address generator for Algorand
  Proposals/xgov-100.md
Labels: o-open_source, s-final, t-tools, p-3

#99 xGov-99 - AlgoLearn Platform; Open-sourced Lecture Series
  Proposals/xgov-99.md
Labels: a-education, o-open_source, s-final, t-tools, p-3

#98 xGov-98 - Launch of Nimblr: Audits, Licensing, Go Live
  Proposals/xgov-98.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-3

#92 xgov-92: DAOsign
  Proposals/xgov-92.md
Labels: o-open_source, s-final, t-tools, a-deployment, p-3

#75 xGov-75 Social Impact Staking for Algo governance
  Proposals/xgov-75.md
Labels: t-community, o-open_source, s-final, a-defi, p-3

#108 xGov-108-Airgap vault & wallet integration via isolated modules
  Proposals/xgov-108.md
Labels: o-open_source, s-final, t-tools, a-deployment, p-3

#96 xgov-96: Cosmic Champs x AlgoBots - Cross-community 3D NFT Collab
  Proposals/xgov-96.md
Labels: t-community, s-final, a-gaming, p-3

#95 xgov-95: Gamify Exploration and Engagement of NFT ecosystem with Open-source browser game
  Proposals/xgov-95.md
Labels: o-open_source, s-final, t-tools, a-nft, p-3

#148 xGov 148 - CompX - CoinTracker+
  Proposals/xgov-148.md
Labels: o-open_source, s-final, t-dapps, a-defi, p-3

#123 xGov-123: AlgoDirectory (directory.algo)
  Proposals/xgov-123.md
Labels: o-open_source, a-user_onboarding, s-final, t-dapps, p-3
